name = "clabernetes"
compatibility_date = "2025-08-09"
preview_urls = true

[assets]
directory = "./docs-site/build/client"
html_handling = "drop-trailing-slash"
not_found_handling = "single-page-application"
