//nolint:gocyclo // Follow one sequential reuse and recovery scenario.
package direct_test

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"reflect"
	"strings"
	"testing"
	"time"

	clabernetestesthelper "github.com/clabernetes/clabernetes/testhelper"
	k8scorev1 "k8s.io/api/core/v1"
)

// TestPlannerPoolReuseAndRecovery checks real reuse across two waves, then worker replacement
// followed by a new plan. It is explicit because it intentionally deletes an installation worker.
func TestPlannerPoolReuseAndRecovery(t *testing.T) {
	if os.Getenv("PLANNER_POOL_E2E") == "" {
		t.Skip("PLANNER_POOL_E2E is not set")
	}
	managerNamespace := os.Getenv("PLANNER_POOL_NAMESPACE")
	if managerNamespace == "" {
		managerNamespace = "c9s-e2e"
	}
	image := os.Getenv("SRL_IMAGE")
	if image == "" {
		image = "ghcr.io/clab-labs/srlinux:25.10.1"
	}
	namespace := clabernetestesthelper.NewTestNamespace("planner-pool")
	clabernetestesthelper.KubectlCreateNamespace(t, namespace)
	defer func() {
		if t.Failed() {
			clabernetestesthelper.DumpNamespaceDiagnostics(t, namespace)
		}
		if !*clabernetestesthelper.SkipCleanup {
			clabernetestesthelper.KubectlDeleteNamespace(t, namespace)
		}
	}()
	clabernetestesthelper.CreateGHCRPullSecret(t, namespace, "pool-registry")
	poolKubectl(
		t,
		"rollout", "status",
		"deployment/clabernetes-planner-pool",
		"-n",
		managerNamespace,
		"--timeout=180s",
	)
	before := poolPodUIDs(t, managerNamespace)
	if len(before) < 1 {
		t.Fatal("no pool workers available")
	}
	profile := `apiVersion: c9s.run/v1alpha1
kind: NodeProfile
metadata:
  name: pool
spec:
  imagePull:
    pullSecrets: [pool-registry]
  expose:
    exposeType: ClusterIP
    disableAutoExpose: true
`
	poolApply(t, namespace, profile)
	for wave := range 2 {
		var manifest strings.Builder
		for index := range 3 {
			kind, nodeImage := "linux", "ghcr.io/srl-labs/network-multitool:latest"
			if index == 0 {
				kind, nodeImage = "nokia_srlinux", image
			}
			fmt.Fprintf(&manifest, `---
apiVersion: c9s.run/v1alpha1
kind: Node
metadata:
  name: wave-%d-node-%d
spec:
  kind: %s
  image: %s
  profileRef:
    name: pool
`, wave, index, kind, nodeImage)
		}
		poolApply(t, namespace, manifest.String())
		for index := range 3 {
			waitForDirectNodeReady(t, namespace, fmt.Sprintf("wave-%d-node-%d", wave, index))
		}
	}
	if after := poolPodUIDs(t, managerNamespace); !reflect.DeepEqual(before, after) {
		t.Fatalf("workers were replaced instead of reused: before=%v after=%v", before, after)
	}
	if disposable := listPods(t, namespace, "app.kubernetes.io/name=clabernetes-planner"); len(
		disposable.Items,
	) != 0 {
		t.Fatal("pool created disposable planner Pods")
	}
	t.Logf("six Nodes planned across two waves using unchanged worker UIDs: %v", before)
	var deleted string
	for name := range before {
		deleted = name

		break
	}
	poolKubectl(t, "delete", "pod", deleted, "-n", managerNamespace, "--wait=true")
	deadline := time.Now().Add(3 * time.Minute)
	for {
		after := poolPodUIDs(t, managerNamespace)
		if len(after) == len(before) && after[deleted] == "" {
			break
		}
		if time.Now().After(deadline) {
			t.Fatal("pool did not replace deleted worker")
		}
		time.Sleep(time.Second)
	}
	nodeName := "wave-1-node-1"
	previous := nodePlanDigest(t, namespace, nodeName)
	poolKubectl(
		t,
		"patch",
		"node.c9s.run",
		nodeName,
		"-n",
		namespace,
		"--type=merge",
		"-p",
		`{"spec":{"env":{"POOL_RECOVERY":"verified"}}}`,
	)
	waitForPlanDigestChange(t, namespace, nodeName, previous)
	waitForDirectNodeReady(t, namespace, nodeName)
	t.Log("new plan and ready device verified after a pool worker was replaced")
}

func poolPodUIDs(t *testing.T, namespace string) map[string]string {
	t.Helper()
	raw := poolKubectl(
		t,
		"get",
		"pods",
		"-n",
		namespace,
		"-l",
		"c9s.run/planner-pool=clabernetes",
		"-o",
		"json",
	)
	var pods k8scorev1.PodList
	if err := json.Unmarshal(raw, &pods); err != nil {
		t.Fatal(err)
	}
	result := map[string]string{}
	for _, pod := range pods.Items {
		if pod.DeletionTimestamp != nil {
			continue
		}
		for _, condition := range pod.Status.Conditions {
			if condition.Type == k8scorev1.PodReady && condition.Status == k8scorev1.ConditionTrue {
				result[pod.Name] = string(pod.UID)
			}
		}
	}

	return result
}

//nolint:gosec // Test-owned kubectl arguments are passed directly without a shell.
func poolKubectl(t *testing.T, args ...string) []byte {
	t.Helper()

	return clabernetestesthelper.Execute(t, exec.CommandContext(t.Context(), "kubectl", args...))
}

//nolint:gosec // The namespace is generated by the test; kubectl uses no shell.
func poolApply(t *testing.T, namespace, manifest string) {
	t.Helper()

	command := exec.CommandContext(t.Context(), "kubectl", "apply", "-n", namespace, "-f", "-")
	command.Stdin = strings.NewReader(manifest)
	clabernetestesthelper.Execute(t, command)
}

// poolPods includes native sidecar startup and restart status for startup regression checks.
func poolPods(t *testing.T, namespace, selector string) k8scorev1.PodList {
	t.Helper()
	var pods k8scorev1.PodList
	if err := json.Unmarshal(poolKubectl(t, "get", "pods", "-n", namespace, "-l", selector, "-o", "json"), &pods); err != nil {
		t.Fatal(err)
	}

	return pods
}
