---
apiVersion: c9s.run/v1alpha1
kind: LauncherProfile
metadata:
  labels:
    clabernetes/app: clabernetes
    clabernetes/name: topo01
    clabernetes/topologyKind: containerlab
    clabernetes/topologyOwner: topo01
  name: topo01
  namespace: notclabernetes
spec:
  expose:
    disableAutoExpose: false
    disableExpose: false
    useNodeMgmtIpv4Address: false
    useNodeMgmtIpv6Address: false
  imagePull:
    insecureRegistries:
    - 1.2.3.4
    pullSecrets:
    - regcred
  resources:
    requests:
      memory: 1Gi
  statusProbes:
    enabled: false
    excludedNodes: null
    nodeProbeConfigurations: null
    probeConfiguration:
      startupSeconds: 0
---
apiVersion: c9s.run/v1alpha1
kind: LauncherProfile
metadata:
  labels:
    clabernetes/app: clabernetes
    clabernetes/name: topo01-srl2
    clabernetes/topologyKind: containerlab
    clabernetes/topologyOwner: topo01
  name: topo01-srl2
  namespace: notclabernetes
spec:
  expose:
    disableAutoExpose: false
    disableExpose: false
    useNodeMgmtIpv4Address: false
    useNodeMgmtIpv6Address: false
  imagePull:
    insecureRegistries:
    - 1.2.3.4
    pullSecrets:
    - regcred
  resources:
    requests:
      memory: 2Gi
  statusProbes:
    enabled: false
    excludedNodes: null
    nodeProbeConfigurations: null
    probeConfiguration:
      startupSeconds: 0
---
apiVersion: c9s.run/v1alpha1
kind: Link
metadata:
  labels:
    clabernetes/app: clabernetes
    clabernetes/name: srl1-e1-1-srl2-e1-1
    clabernetes/topologyKind: containerlab
    clabernetes/topologyOwner: topo01
  name: srl1-e1-1-srl2-e1-1
  namespace: notclabernetes
spec:
  connectivity: slurpeeth
  endpointA:
    interfaceName: e1-1
    nodeName: srl1
  endpointB:
    interfaceName: e1-1
    nodeName: srl2
---
apiVersion: c9s.run/v1alpha1
kind: Node
metadata:
  labels:
    clabernetes/app: clabernetes
    clabernetes/name: srl1
    clabernetes/topologyKind: containerlab
    clabernetes/topologyNode: srl1
    clabernetes/topologyOwner: topo01
  name: srl1
  namespace: notclabernetes
spec:
  filesFromConfigMap:
  - configMapName: topo01-srl1-startup-config
    configMapPath: REPLACED
    filePath: srl1.cfg
    mode: read
  - configMapName: topo01-srl1-files
    configMapPath: REPLACED
    filePath: taco/srl1.license
    mode: read
  image: ghcr.io/nokia/srlinux
  kind: srl
  launcherProfileRef:
    name: topo01
  license: taco/srl1.license
  startup-config: srl1.cfg

---
apiVersion: c9s.run/v1alpha1
kind: Node
metadata:
  labels:
    clabernetes/app: clabernetes
    clabernetes/name: srl2
    clabernetes/topologyKind: containerlab
    clabernetes/topologyNode: srl2
    clabernetes/topologyOwner: topo01
  name: srl2
  namespace: notclabernetes
spec:
  binds:
  - __clabDir__/potato.txt:/potato.txt
  - __clabNodeDir__/potato.txt:/nodedir-potato.txt
  filesFromConfigMap:
  - configMapName: topo01-srl2-files
    configMapPath: REPLACED
    filePath: /some/dir/clabernetes/clabverter/test-fixtures/clabversiontest/potato.txt
    mode: read
  - configMapName: topo01-srl2-files
    configMapPath: REPLACED
    filePath: /some/dir/clabernetes/clabverter/test-fixtures/clabversiontest/srl2/potato.txt
    mode: read
  - configMapName: topo01-srl2-startup-config
    configMapPath: REPLACED
    filePath: srl2.cfg
    mode: read
  - configMapName: topo01-srl2-files
    configMapPath: REPLACED
    filePath: srl2.license
    mode: read
  image: ghcr.io/nokia/srlinux
  kind: srl
  launcherProfileRef:
    name: topo01-srl2
  license: srl2.license
  startup-config: srl2.cfg

---
apiVersion: c9s.run/v1alpha1
kind: Node
metadata:
  labels:
    clabernetes/app: clabernetes
    clabernetes/name: sros1
    clabernetes/topologyKind: containerlab
    clabernetes/topologyNode: sros1
    clabernetes/topologyOwner: topo01
  name: sros1
  namespace: notclabernetes
spec:
  filesFromConfigMap:
  - configMapName: topo01-sros1-files
    configMapPath: REPLACED
    filePath: taco/srl1.license
    mode: read
  image: nokia_sros:latest
  kind: nokia_sros
  launcherProfileRef:
    name: topo01
  license: taco/srl1.license

---
apiVersion: c9s.run/v1alpha1
kind: Node
metadata:
  labels:
    clabernetes/app: clabernetes
    clabernetes/name: sros2
    clabernetes/topologyKind: containerlab
    clabernetes/topologyNode: sros2
    clabernetes/topologyOwner: topo01
  name: sros2
  namespace: notclabernetes
spec:
  filesFromConfigMap:
  - configMapName: topo01-sros2-files
    configMapPath: REPLACED
    filePath: srl2.license
    mode: read
  healthcheck:
    interval: 1
    start-period: 5
    test:
    - CMD-SHELL
    - cat /etc/os-release
  image: nokia_sros:latest
  kind: nokia_sros
  launcherProfileRef:
    name: topo01
  license: srl2.license
