---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    revision: "{{ .Release.Revision }}"
    c9s.run/app: {{ .Values.appName }}
    c9s.run/name: "{{ .Values.appName }}-clicker-cluster-role"
    c9s.run/component: cluster-role
    {{- if .Values.globalLabels }}
{{ .Values.globalLabels | toYaml | indent 4 }}
    {{- end }}
  {{- if .Values.globalAnnotations }}
  annotations:
{{ .Values.globalAnnotations | toYaml | indent 4 }}
  {{- end }}
  name: "{{ .Values.appName }}-clicker-cluster-role"
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - create
      - watch
      - delete