apiVersion: c9s.run/v1alpha1
kind: NodeProfile
metadata:
  labels:
    c9s.run/app: clabernetes
    c9s.run/name: topology-basic
    c9s.run/topologyKind: containerlab
    c9s.run/topologyOwner: topology-basic
  name: topology-basic
  namespace: NAMESPACE
  ownerReferences:
    - apiVersion: c9s.run/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Topology
      name: topology-basic
spec:
  expose:
    disableAutoExpose: false
    disableExpose: false
    useNodeMgmtIpv4Address: false
    useNodeMgmtIpv6Address: false
  statusProbes:
    enabled: false
    probeConfiguration:
      startupSeconds: 0
status: {}
