apiVersion: v1
kind: Service
metadata:
  labels:
    c9s.run/app: clabernetes
    c9s.run/name: srl1-vx
    c9s.run/topologyNode: srl1
    c9s.run/topologyOwner: topology-basic
    c9s.run/topologyServiceType: fabric
  name: srl1-vx
  namespace: NAMESPACE
  ownerReferences:
    - apiVersion: c9s.run/v1alpha1
      kind: Node
      name: srl1
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: vxlan
      port: 14789
      protocol: UDP
      targetPort: 14789
    - name: slurpeeth
      port: 4799
      protocol: TCP
      targetPort: 4799
  publishNotReadyAddresses: true
  selector:
    c9s.run/app: clabernetes
    c9s.run/name: srl1
    c9s.run/topologyNode: srl1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
