apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Topology
metadata:
  annotations: {}
  name: topology-basic
  namespace: NAMESPACE
spec:
  connectivity: vxlan
  definition:
    containerlab: |-
      name: topology-basic

      topology:
        nodes:
          srl1:
            kind: srl
            image: ghcr.io/nokia/srlinux
  deployment:
    containerlabTimeout: ""
    persistence:
      enabled: false
    scheduling: {}
  expose:
    disableAutoExpose: false
    disableExpose: false
    exposeType: LoadBalancer
  imagePull: {}
  naming: global
  statusProbes:
    enabled: false
    probeConfiguration:
      startupSeconds: 0
status:
  kind: containerlab
  nodeCount: 1
  removeTopologyPrefix: false
