apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: srl1
    clabernetes/app: clabernetes
    clabernetes/name: srl1
    clabernetes/topologyNode: srl1
    clabernetes/topologyOwner: topology-basic
  name: srl1
  namespace: NAMESPACE
  ownerReferences:
    - apiVersion: clabernetes.containerlab.dev/v1alpha1
      kind: Node
      name: srl1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: srl1
      clabernetes/app: clabernetes
      clabernetes/name: srl1
      clabernetes/topologyNode: srl1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        clabernetes/linkAttachmentsDigest: acbb29dba858160627ce8ac9f60599d09f36674686ab4131211e03f412711fe2
        clabernetes/nodeConfigDigest: e7c66a3da651e14784927a8a228df681b3363f1c3460ec356c6651561183ee3a
      labels:
        app.kubernetes.io/name: srl1
        clabernetes/app: clabernetes
        clabernetes/name: srl1
        clabernetes/topologyNode: srl1
        clabernetes/topologyOwner: topology-basic
    spec:
      containers:
        - command:
            - /clabernetes/manager
            - launch
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: APP_NAME
              value: clabernetes
            - name: MANAGER_NAMESPACE
              value: clabernetes
            - name: LAUNCHER_CRI_KIND
              value: containerd
            - name: LAUNCHER_IMAGE_PULL_THROUGH_MODE
              value: auto
            - name: LAUNCHER_LOGGER_LEVEL
              value: debug
            - name: LAUNCHER_NODE_NAME
              value: srl1
            - name: LAUNCHER_NODE_IMAGE
              value: ghcr.io/nokia/srlinux
            - name: LAUNCHER_IN_CLUSTER_DNS_SUFFIX
              value: svc.cluster.local
            - name: LAUNCHER_CONTAINERLAB_VERSION
            - name: LAUNCHER_CONTAINERLAB_TIMEOUT
            - name: LAUNCHER_PRIVILEGED
              value: "true"
          imagePullPolicy: IfNotPresent
          name: srl1
          ports:
            - containerPort: 14789
              name: vxlan
              protocol: UDP
            - containerPort: 4799
              name: slurpeeth
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
          securityContext:
            privileged: true
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/docker
              name: docker
            - mountPath: /clabernetes/podinfo
              name: podinfo
              readOnly: true
          workingDir: /clabernetes
      dnsPolicy: ClusterFirst
      hostname: srl1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: clabernetes-launcher-service-account
      serviceAccountName: clabernetes-launcher-service-account
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: docker
        - downwardAPI:
            defaultMode: 292
            items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations[clabernetes/linkAttachmentsDigest]
                path: link-attachments-digest
          name: podinfo
status: {}
