apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Link
metadata:
  labels:
    clabernetes/app: clabernetes
    clabernetes/name: srl1-e1-1-srl2-e1-1
    clabernetes/topologyKind: containerlab
    clabernetes/topologyOwner: topology-basic
  name: srl1-e1-1-srl2-e1-1
  namespace: NAMESPACE
  ownerReferences:
    - apiVersion: clabernetes.containerlab.dev/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Topology
      name: topology-basic
spec:
  connectivity: vxlan
  endpointA:
    interfaceName: e1-1
    nodeName: srl1
  endpointB:
    interfaceName: e1-1
    nodeName: srl2
status:
  resolvedEndpoints:
    endpointA:
      nodeName: srl1
    endpointB:
      nodeName: srl2
  tunnelID: 1
