apiVersion: c9s.run/v1alpha1
kind: Link
metadata:
  finalizers:
    - c9s.run/host-endpoint
  labels:
    c9s.run/app: clabernetes
    c9s.run/name: srl1-e1-3-host-eth13
    c9s.run/topologyKind: containerlab
    c9s.run/topologyOwner: topology-basic
  name: srl1-e1-3-host-eth13
  namespace: NAMESPACE
  ownerReferences:
    - apiVersion: c9s.run/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Topology
      name: topology-basic
spec:
  connectivity: vxlan
  endpointA:
    interfaceName: e1-3
    nodeName: srl1
  endpointB:
    interfaceName: eth13
    nodeName: host
status:
  resolvedEndpoints:
    endpointA:
      nodeName: srl1
    endpointB:
      nodeName: host
