apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Link
metadata:
  labels:
    clabernetes/app: clabernetes
    clabernetes/linkEndpointA: srl1
    clabernetes/linkEndpointB: srl2
    clabernetes/name: topology-basic
    clabernetes/topologyKind: containerlab
    clabernetes/topologyOwner: topology-basic
  name: topology-basic-srl1-e1-1-srl2-e1-1
  namespace: NAMESPACE
  ownerReferences:
    - apiVersion: clabernetes.containerlab.dev/v1alpha1
      kind: Topology
      name: topology-basic
spec:
  endpointA:
    interfaceName: e1-1
    nodeName: srl1
  endpointB:
    interfaceName: e1-1
    nodeName: srl2
  topologyName: topology-basic
status:
  tunnelID: 1
