apiVersion: c9s.run/v1alpha1
kind: Node
metadata:
  labels:
    c9s.run/app: clabernetes
    c9s.run/name: srl2
    c9s.run/topologyKind: containerlab
    c9s.run/topologyNode: srl2
    c9s.run/topologyOwner: topology-basic
  name: srl2
  namespace: NAMESPACE
  ownerReferences:
    - apiVersion: c9s.run/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Topology
      name: topology-basic
spec:
  image: ghcr.io/nokia/srlinux
  kind: srl
  profileRef:
    name: topology-basic
status:
  appliedProfile:
    name: topology-basic
  exposedPorts:
    ports:
      - destinationPort: 21
        exposePort: 21
        protocol: TCP
      - destinationPort: 22
        exposePort: 22
        protocol: TCP
      - destinationPort: 23
        exposePort: 23
        protocol: TCP
      - destinationPort: 80
        exposePort: 80
        protocol: TCP
      - destinationPort: 443
        exposePort: 443
        protocol: TCP
      - destinationPort: 830
        exposePort: 830
        protocol: TCP
      - destinationPort: 5000
        exposePort: 5000
        protocol: TCP
      - destinationPort: 5900
        exposePort: 5900
        protocol: TCP
      - destinationPort: 6030
        exposePort: 6030
        protocol: TCP
      - destinationPort: 9339
        exposePort: 9339
        protocol: TCP
      - destinationPort: 9340
        exposePort: 9340
        protocol: TCP
      - destinationPort: 9559
        exposePort: 9559
        protocol: TCP
      - destinationPort: 57400
        exposePort: 57400
        protocol: TCP
      - destinationPort: 161
        exposePort: 161
        protocol: UDP
