apiVersion: v1
kind: Service
metadata:
  labels:
    clabernetes/app: clabernetes
    clabernetes/name: srl1-vx
    clabernetes/topologyNode: srl1
    clabernetes/topologyOwner: topology-basic
    clabernetes/topologyServiceType: fabric
  name: srl1-vx
  namespace: NAMESPACE
  ownerReferences:
    - apiVersion: clabernetes.containerlab.dev/v1alpha1
      kind: Node
      name: srl1
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: vxlan
      port: 14789
      protocol: UDP
      targetPort: 14789
    - name: slurpeeth
      port: 4799
      protocol: TCP
      targetPort: 4799
  selector:
    clabernetes/app: clabernetes
    clabernetes/name: srl1
    clabernetes/topologyNode: srl1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
