apiVersion: v1
kind: Service
metadata:
  labels:
    c9s.run/app: clabernetes
    c9s.run/name: srl2-wire
    c9s.run/topologyNode: srl2
    c9s.run/topologyOwner: topology-basic
    c9s.run/topologyServiceType: fabric
  name: srl2-wire
  namespace: NAMESPACE
  ownerReferences:
    - apiVersion: c9s.run/v1alpha1
      kind: Node
      name: srl2
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: wire
      port: 14790
      protocol: UDP
      targetPort: 14790
  publishNotReadyAddresses: true
  selector:
    c9s.run/app: clabernetes
    c9s.run/name: srl2
    c9s.run/topologyNode: srl2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
