//nolint:funlen,gocognit,gocyclo,maintidx,mnd,nlreturn,wsl_v5 // Preparation guards fail closed at the artifact boundary.
package deviceplan

import (
	"context"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strings"

	clabnodes "github.com/srl-labs/containerlab/nodes"
)

const (
	importedPreparationSource = "containerlab/imported-prepare"
	maxPreparedPayloadBytes   = 64 << 20
)

// Preparer reruns deterministic imported initialization/preparation inside a target Pod and
// stages only artifacts whose path, mode, and digest were accepted by planning.
type Preparer struct {
	Adapter     Adapter
	PayloadRoot string
	HTTPClient  *http.Client
	// PersistentNodeIDs marks Nodes whose artifact volume is a PersistentVolumeClaim; their
	// planned artifacts publish through the staging-ledger policy instead of unconditionally.
	PersistentNodeIDs map[string]bool
	// ResetTokens carries the projected device-state reset token per Node. A token that
	// differs from the Node ledger's acknowledged token wipes and re-seeds its artifacts.
	ResetTokens map[string]string
	// Output receives human-readable preparation reports (preserved files, honored resets).
	Output io.Writer
}

// Prepare verifies plan identity and materializes imported preparation artifacts below opaque,
// content-addressed Node directories. The same full imported hook sequence used by planning is
// recorded again, so preparation and lifecycle-generated byte artifacts share one verified path.
func (p Preparer) Prepare(
	ctx context.Context,
	input Input,
	plan Plan,
	artifactRoot string,
) error {
	if ctx == nil {
		return planningError(ErrorInvalidInput, "context", "context is nil", nil)
	}
	normalizedInput, err := NormalizeInput(input)
	if err != nil {
		return err
	}
	normalizedPlan, err := NormalizePlan(plan)
	if err != nil {
		return err
	}
	inputDigest, err := normalizedInput.Digest()
	if err != nil {
		return err
	}
	if normalizedPlan.InputDigest != inputDigest ||
		!reflect.DeepEqual(normalizedPlan.Compatibility, normalizedInput.Compatibility) ||
		normalizedPlan.Planner.Revision != p.Adapter.Revision {
		return &Error{
			Code: ErrorInvariant, Field: "preparation.identity",
			Behavior: behaviorArtifactGeneration,
			Message:  "plan and normalized preparation input identities differ",
		}
	}
	finishEntropy, err := p.Adapter.beginEntropy(normalizedInput)
	if err != nil {
		return err
	}
	entropyFinished := false
	finishOnce := func() {
		if !entropyFinished {
			entropyFinished = true
			finishEntropy()
		}
	}
	defer finishOnce()
	artifactRoot = filepath.Clean(artifactRoot)
	if !filepath.IsAbs(artifactRoot) || artifactRoot == string(filepath.Separator) {
		return &Error{
			Code: ErrorInvalidInput, Field: "preparation.artifactRoot",
			Behavior: behaviorArtifactGeneration,
			Message:  "artifact root must be a scoped absolute path",
		}
	}
	if err = os.MkdirAll(artifactRoot, 0o700); err != nil {
		return planningError(
			ErrorSideEffect,
			"preparation.artifactRoot",
			"cannot create artifact root",
			err,
		)
	}

	scratchRoot, err := os.MkdirTemp("", "clabernetes-device-prepare-")
	if err != nil {
		return planningError(
			ErrorSideEffect,
			"preparation.workspace",
			"cannot create workspace",
			err,
		)
	}
	defer func() { _ = os.RemoveAll(scratchRoot) }()
	registry := p.Adapter.Registry
	if registry == nil {
		registry = NewContainerlabRegistry()
		if err = validateLiveCompatibility(registry, normalizedInput.Compatibility); err != nil {
			return err
		}
	}
	evaluation, err := evaluateInWorkspace(
		ctx,
		normalizedInput,
		inputDigest,
		registry,
		scratchRoot,
		p.PayloadRoot,
		p.Adapter.CertificateRoot,
		true,
	)
	if err != nil {
		return err
	}

	expected := map[string]FilePlan{}
	for _, file := range normalizedPlan.Files {
		if file.SourceKind != FileSourceGenerator && file.SourceKind != FileSourceCertificate {
			continue
		}
		expected[file.NodeID+"\x00"+file.ArtifactPath] = file
	}
	type acceptedArtifact struct {
		node     *EvaluatedNode
		artifact GeneratedArtifact
	}
	accepted := []acceptedArtifact{}
	for index := range evaluation.Nodes {
		node := &evaluation.Nodes[index]
		for _, artifact := range node.GeneratedArtifacts {
			key := node.Input.ID + "\x00" + artifact.Path
			file, exists := expected[key]
			if mismatch := preparedArtifactMismatch(file, artifact, exists); mismatch != "" {
				return &Error{
					Code: ErrorInvariant, NodeID: node.Input.ID, Field: "preparation.artifacts",
					Behavior: behaviorArtifactGeneration,
					Message:  "generated artifact " + mismatch + " differs from the accepted plan",
				}
			}
			accepted = append(accepted, acceptedArtifact{node: node, artifact: artifact})
			delete(expected, key)
		}
	}
	if len(expected) != 0 {
		return &Error{
			Code: ErrorInvariant, Field: "preparation.artifacts",
			Behavior: behaviorArtifactGeneration,
			Message:  "planned preparation artifact was not regenerated",
		}
	}
	// The verified render above used the exact planning inputs and is the determinism proof. A
	// second render with the Pod's runtime management identity supplies the bytes packages
	// actually boot from; it may change only regular generator-file content, never artifact
	// topology or metadata.
	divergent, runtimeLabDirs, cleanupRuntime, err := p.renderRuntimeManagementArtifacts(
		ctx,
		normalizedInput,
		normalizedPlan,
		inputDigest,
		registry,
		finishOnce,
	)
	if err != nil {
		return err
	}
	defer cleanupRuntime()
	policy, err := p.newStagingPolicy(normalizedInput, normalizedPlan, artifactRoot)
	if err != nil {
		return err
	}
	// Leave parent directories preparation-writable while publishing leaves. Apply package
	// directory modes, ownership, and extended attributes deepest-first after every leaf exists.
	for _, item := range accepted {
		if item.artifact.Kind == ArtifactDirectory {
			continue
		}
		source, artifact := item.node.scratchLabDir, item.artifact
		if replacement, exists := divergent[item.node.Input.ID+"\x00"+item.artifact.Path]; exists {
			source, artifact = runtimeLabDirs[item.node.Input.ID], replacement
		}
		publish, publishErr := policy.shouldPublish(
			artifactRoot,
			item.node.Input.ID,
			artifact.Kind,
			artifact.Path,
			artifact.Digest,
		)
		if publishErr != nil {
			return withNodeID(publishErr, item.node.Input.ID)
		}
		if !publish {
			continue
		}
		if err = stagePreparedArtifact(
			source,
			artifactRoot,
			item.node.Input.ID,
			artifact,
		); err != nil {
			return withNodeID(err, item.node.Input.ID)
		}
		policy.recordPublished(item.node.Input.ID, artifact.Path, artifact.Digest)
	}
	for _, item := range slices.Backward(accepted) {
		if item.artifact.Kind != ArtifactDirectory {
			continue
		}
		if err = stagePreparedArtifact(
			item.node.scratchLabDir,
			artifactRoot,
			item.node.Input.ID,
			item.artifact,
		); err != nil {
			return withNodeID(err, item.node.Input.ID)
		}
	}
	for _, node := range normalizedInput.Nodes {
		digests := map[string]string{}
		for key, artifact := range divergent {
			if strings.HasPrefix(key, node.ID+"\x00") {
				digests[artifact.Path] = artifact.Digest
			}
		}
		if err = writeRuntimeArtifactDigests(artifactRoot, node.ID, digests); err != nil {
			return withNodeID(err, node.ID)
		}
	}
	err = p.stagePayloads(ctx, normalizedInput, normalizedPlan, artifactRoot, policy)
	if err != nil {
		return err
	}

	return policy.flush(artifactRoot)
}

// renderRuntimeManagementArtifacts reruns imported generation with the Pod's runtime management
// identity and returns the regular artifacts whose content diverged from the plan, keyed by
// nodeID and path, together with each node's runtime workspace. Certificate material stays
// byte-identical because both renders load it from the same mounted planning infrastructure
// under the same entropy; every non-content difference fails closed, because management
// completion must not change artifact topology or metadata.
//
//nolint:gocognit,gocyclo // Each branch rejects one divergence class explicitly.
func (p Preparer) renderRuntimeManagementArtifacts(
	ctx context.Context,
	input Input,
	plan Plan,
	inputDigest string,
	registry *clabnodes.NodeRegistry,
	restartEntropy func(),
) (map[string]GeneratedArtifact, map[string]string, func(), error) {
	cleanup := func() {}
	completed := completeRuntimeManagement(
		input.Management,
		plan.Management,
		p.Adapter.PodDNSServers,
	)
	if reflect.DeepEqual(completed, input.Management) {
		return nil, nil, cleanup, nil
	}
	runtimeInput := input
	runtimeInput.Management = completed
	scratchRoot, err := os.MkdirTemp("", "clabernetes-device-prepare-runtime-")
	if err != nil {
		return nil, nil, cleanup, planningError(
			ErrorSideEffect,
			"preparation.runtimeWorkspace",
			"cannot create runtime workspace",
			err,
		)
	}
	cleanup = func() { _ = os.RemoveAll(scratchRoot) }
	// A fresh entropy session over the original input digest replays the exact randomness of
	// the verified render, so the only permitted divergence source is the completed management
	// identity.
	restartEntropy()
	finishEntropy, err := beginImportedEntropy(
		inputDigest,
		input.EntropyDigest,
		p.Adapter.EntropyRoot,
	)
	if err != nil {
		return nil, nil, cleanup, err
	}
	defer finishEntropy()
	evaluation, err := evaluateInWorkspace(
		ctx,
		runtimeInput,
		inputDigest,
		registry,
		scratchRoot,
		p.PayloadRoot,
		p.Adapter.CertificateRoot,
		false,
	)
	if err != nil {
		return nil, nil, cleanup, err
	}
	planned := map[string]FilePlan{}
	for _, file := range plan.Files {
		if file.SourceKind != FileSourceGenerator && file.SourceKind != FileSourceCertificate {
			continue
		}
		planned[file.NodeID+"\x00"+file.ArtifactPath] = file
	}
	divergent := map[string]GeneratedArtifact{}
	labDirs := map[string]string{}
	for index := range evaluation.Nodes {
		node := &evaluation.Nodes[index]
		labDirs[node.Input.ID] = node.scratchLabDir
		for _, artifact := range node.GeneratedArtifacts {
			key := node.Input.ID + "\x00" + artifact.Path
			file, exists := planned[key]
			if !exists {
				return nil, nil, cleanup, &Error{
					Code: ErrorInvariant, NodeID: node.Input.ID,
					Field: fieldPreparationRuntimeArtifacts, Behavior: behaviorArtifactGeneration,
					Message: "management completion added an artifact absent from the plan",
				}
			}
			delete(planned, key)
			if file.Digest == artifact.Digest {
				if mismatch := preparedArtifactMismatch(file, artifact, true); mismatch != "" {
					return nil, nil, cleanup, &Error{
						Code: ErrorInvariant, NodeID: node.Input.ID,
						Field:    fieldPreparationRuntimeArtifacts,
						Behavior: behaviorArtifactGeneration,
						Message: "management completion changed " + mismatch +
							" of artifact " + artifact.Path,
					}
				}

				continue
			}
			metadataOnly := artifact
			metadataOnly.Digest = file.Digest
			if artifact.Kind != ArtifactRegular ||
				preparedArtifactMismatch(file, metadataOnly, true) != "" {
				return nil, nil, cleanup, &Error{
					Code: ErrorInvariant, NodeID: node.Input.ID,
					Field: fieldPreparationRuntimeArtifacts, Behavior: behaviorArtifactGeneration,
					Message: "management completion may change only regular generator content" +
						"; artifact " + artifact.Path,
				}
			}
			divergent[key] = artifact
		}
	}
	if len(planned) != 0 {
		return nil, nil, cleanup, &Error{
			Code: ErrorInvariant, Field: fieldPreparationRuntimeArtifacts,
			Behavior: behaviorArtifactGeneration,
			Message:  "management completion removed a planned artifact",
		}
	}
	return divergent, labDirs, cleanup, nil
}

func preparedArtifactMismatch(file FilePlan, artifact GeneratedArtifact, exists bool) string {
	if !exists {
		return "identity"
	}
	for _, comparison := range []struct {
		matches bool
		name    string
	}{
		{file.Digest == artifact.Digest, "digest"},
		{file.Mode == artifact.Mode, "mode"},
		{file.ArtifactKind == artifact.Kind, fieldKind},
		{file.LinkTarget == artifact.LinkTarget, "link target"},
		{file.SourceReference == artifact.SourceReference, "provenance"},
		{reflect.DeepEqual(file.UID, artifact.UID), "owner"},
		{reflect.DeepEqual(file.GID, artifact.GID), "group"},
		{
			reflect.DeepEqual(
				file.ExtendedAttributes,
				mapGeneratedExtendedAttributes(artifact.ExtendedAttributes),
			),
			"extended attributes",
		},
	} {
		if !comparison.matches {
			return comparison.name
		}
	}

	return ""
}

func (p Preparer) stagePayloads(
	ctx context.Context,
	input Input,
	plan Plan,
	artifactRoot string,
	policy *stagingPolicy,
) error {
	if len(input.Payloads) == 0 {
		return nil
	}
	payloadRoot := filepath.Clean(p.PayloadRoot)
	if !filepath.IsAbs(payloadRoot) || payloadRoot == string(filepath.Separator) {
		return &Error{
			Code: ErrorInvalidInput, Field: "preparation.payloadRoot",
			Behavior: behaviorPayloadStaging,
			Message:  "payload root must be a scoped absolute path",
		}
	}
	files := map[string]FilePlan{}
	contentByIdentity := map[string][]byte{}
	for _, file := range plan.Files {
		if file.SourceKind != FileSourcePayload {
			continue
		}
		if _, exists := files[file.SourceReference]; exists {
			return &Error{
				Code: ErrorInvariant, Field: fieldPreparationPayloads,
				Behavior: behaviorPayloadStaging,
				Message:  "one payload identity is referenced by multiple file plans",
			}
		}
		files[file.SourceReference] = file
	}
	for _, payload := range input.Payloads {
		file, exists := files[payload.ID]
		if !exists || file.NodeID != payload.NodeID || file.Destination != payload.Destination ||
			file.Mode != payload.Mode || file.Digest != payload.Digest {
			return &Error{
				Code: ErrorInvariant, NodeID: payload.NodeID, Field: fieldPreparationPayloads,
				Behavior: behaviorPayloadStaging,
				Message:  "payload input differs from the accepted file plan",
			}
		}
		contentIdentity := strings.Join([]string{
			string(payload.Kind), payload.Reference, payload.Digest,
		}, "\x00")
		content, cached := contentByIdentity[contentIdentity]
		if !cached {
			var err error
			content, err = p.readPayload(ctx, payloadRoot, payload)
			if err != nil {
				return withNodeID(err, payload.NodeID)
			}
			contentByIdentity[contentIdentity] = content
		}
		if Digest(content) != payload.Digest {
			return &Error{
				Code: ErrorInvariant, NodeID: payload.NodeID, Field: fieldPreparationPayloads,
				Behavior: behaviorPayloadStaging,
				Message:  "payload bytes do not match the accepted digest",
			}
		}
		publish, publishErr := policy.shouldPublish(
			artifactRoot,
			payload.NodeID,
			ArtifactRegular,
			file.ArtifactPath,
			payload.Digest,
		)
		if publishErr != nil {
			return withNodeID(publishErr, payload.NodeID)
		}
		if publish {
			if stageErr := stageArtifactContent(
				content,
				artifactRoot,
				payload.NodeID,
				file.ArtifactPath,
				file.Mode,
				file.UID,
				file.GID,
				nil,
				behaviorPayloadStaging,
			); stageErr != nil {
				return withNodeID(stageErr, payload.NodeID)
			}
			policy.recordPublished(payload.NodeID, file.ArtifactPath, payload.Digest)
		}
		delete(files, payload.ID)
	}
	if len(files) != 0 {
		return &Error{
			Code: ErrorInvariant, Field: fieldPreparationPayloads, Behavior: behaviorPayloadStaging,
			Message: "accepted file plan references an unavailable payload input",
		}
	}

	return nil
}

func (p Preparer) readPayload(
	ctx context.Context,
	payloadRoot string,
	payload PayloadInput,
) ([]byte, error) {
	switch payload.Kind {
	case PayloadConfigMap, PayloadSecret:
		source := filepath.Join(payloadRoot, ArtifactNodeDirectory(payload.ID), "source")
		content, err := os.ReadFile( //nolint:gosec // reads are confined to plan-scoped roots.
			source,
		)
		if err != nil {
			return nil, planningError(
				ErrorSideEffect,
				fieldPreparationPayloads,
				"cannot read mounted payload source",
				err,
			)
		}

		return content, nil
	case PayloadURL:
		client := p.HTTPClient
		if client == nil {
			client = securePayloadHTTPClient()
		}

		return readURLPayload(ctx, client, payload.Reference)
	default:
		return nil, &Error{
			Code: ErrorUnsupported, Field: fieldPreparationPayloads,
			Behavior: behaviorPayloadStaging,
			Message:  "payload source has no direct preparation reader",
		}
	}
}

func stagePreparedArtifact(
	scratchRoot,
	artifactRoot,
	nodeID string,
	artifact GeneratedArtifact,
) error {
	source := filepath.Join(scratchRoot, filepath.FromSlash(artifact.Path))
	if artifact.Kind == ArtifactDirectory {
		return stageArtifactDirectory(
			artifactRoot,
			nodeID,
			artifact.Path,
			artifact.Mode,
			artifact.UID,
			artifact.GID,
			artifact.ExtendedAttributes,
			behaviorArtifactGeneration,
		)
	}
	if artifact.Kind == ArtifactSymlink {
		target, err := os.Readlink(source)
		if err != nil || target != artifact.LinkTarget ||
			Digest([]byte(target)) != artifact.Digest {
			return &Error{
				Code: ErrorInvariant, Field: "preparation.source",
				Behavior: behaviorArtifactGeneration,
				Message:  "regenerated symbolic link changed after inventory", cause: err,
			}
		}

		return stageArtifactSymlink(
			artifactRoot,
			nodeID,
			artifact.Path,
			target,
			artifact.UID,
			artifact.GID,
			artifact.ExtendedAttributes,
			behaviorArtifactGeneration,
		)
	}
	content, err := os.ReadFile( //nolint:gosec // reads are confined to plan-scoped roots.
		source,
	)
	if err != nil {
		return planningError(
			ErrorSideEffect,
			"preparation.source",
			"cannot read regenerated artifact",
			err,
		)
	}
	if Digest(content) != artifact.Digest {
		return &Error{
			Code: ErrorInvariant, Field: "preparation.source", Behavior: behaviorArtifactGeneration,
			Message: "regenerated artifact changed after inventory",
		}
	}

	return stageArtifactContent(
		content,
		artifactRoot,
		nodeID,
		artifact.Path,
		artifact.Mode,
		artifact.UID,
		artifact.GID,
		artifact.ExtendedAttributes,
		behaviorArtifactGeneration,
	)
}

func stageArtifactContent(
	content []byte,
	artifactRoot,
	nodeID,
	artifactPath string,
	mode uint32,
	uid,
	gid *int64,
	extendedAttributes []generatedExtendedAttribute,
	behavior string,
) error {
	destination, err := prepareArtifactDestination(
		artifactRoot,
		nodeID,
		artifactPath,
		behavior,
	)
	if err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(destination), ".c9s-stage-")
	if err != nil {
		return planningError(
			ErrorSideEffect,
			fieldPreparationDestination,
			"cannot create staged artifact",
			err,
		)
	}
	temporaryName := temporary.Name()
	defer func() { _ = os.Remove(temporaryName) }()
	_, err = temporary.Write(content)
	if err == nil {
		err = applyGeneratedArtifactMetadata(
			temporaryName,
			false,
			uid,
			gid,
			nil,
		)
	}
	if err == nil {
		err = temporary.Chmod(os.FileMode(mode))
	}
	if err == nil {
		err = applyGeneratedArtifactMetadata(
			temporaryName,
			false,
			nil,
			nil,
			extendedAttributes,
		)
	}
	if closeErr := temporary.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return planningError(
			ErrorSideEffect,
			fieldPreparationDestination,
			"cannot write staged artifact",
			err,
		)
	}
	if existing, statErr := os.Lstat(destination); statErr == nil &&
		!existing.Mode().IsRegular() {
		return &Error{
			Code: ErrorUnsupported, Field: fieldPreparationDestination,
			Behavior: behavior, Message: "artifact destination is not a regular file",
		}
	} else if statErr != nil && !os.IsNotExist(statErr) {
		return planningError(
			ErrorSideEffect,
			fieldPreparationDestination,
			"cannot inspect artifact destination",
			statErr,
		)
	}
	if err = os.Rename(temporaryName, destination); err != nil {
		return planningError(
			ErrorSideEffect,
			fieldPreparationDestination,
			"cannot publish staged artifact",
			err,
		)
	}

	return nil
}

func stageArtifactSymlink(
	artifactRoot,
	nodeID,
	artifactPath,
	target string,
	uid,
	gid *int64,
	extendedAttributes []generatedExtendedAttribute,
	behavior string,
) error {
	destination, err := prepareArtifactDestination(
		artifactRoot,
		nodeID,
		artifactPath,
		behavior,
	)
	if err != nil {
		return err
	}
	if existing, statErr := os.Lstat(destination); statErr == nil &&
		existing.Mode()&os.ModeSymlink == 0 {
		return &Error{
			Code: ErrorUnsupported, Field: fieldPreparationDestination,
			Behavior: behavior, Message: "symbolic-link destination has another file type",
		}
	} else if statErr != nil && !os.IsNotExist(statErr) {
		return planningError(
			ErrorSideEffect,
			fieldPreparationDestination,
			"cannot inspect symbolic-link destination",
			statErr,
		)
	}
	temporary, err := os.CreateTemp(filepath.Dir(destination), ".c9s-link-")
	if err != nil {
		return planningError(
			ErrorSideEffect,
			fieldPreparationDestination,
			"cannot reserve staged symbolic link",
			err,
		)
	}
	temporaryName := temporary.Name()
	if err = temporary.Close(); err == nil {
		err = os.Remove(temporaryName)
	}
	if err == nil {
		err = os.Symlink(target, temporaryName)
	}
	if err == nil {
		err = applyGeneratedArtifactMetadata(
			temporaryName,
			true,
			uid,
			gid,
			extendedAttributes,
		)
	}
	if err != nil {
		return planningError(
			ErrorSideEffect,
			fieldPreparationDestination,
			"cannot create staged symbolic link",
			err,
		)
	}
	defer func() { _ = os.Remove(temporaryName) }()
	if err = os.Rename(temporaryName, destination); err != nil {
		return planningError(
			ErrorSideEffect,
			fieldPreparationDestination,
			"cannot publish staged symbolic link",
			err,
		)
	}

	return nil
}

func stageArtifactDirectory(
	artifactRoot,
	nodeID,
	artifactPath string,
	mode uint32,
	uid,
	gid *int64,
	extendedAttributes []generatedExtendedAttribute,
	behavior string,
) error {
	nodeRoot := filepath.Join(artifactRoot, ArtifactNodeDirectory(nodeID))
	destination := nodeRoot
	if artifactPath == "." {
		if err := ensureNoSymlinkParents(nodeRoot, nodeRoot); err != nil {
			return err
		}
	} else {
		var err error
		destination, err = prepareArtifactDestination(
			artifactRoot,
			nodeID,
			artifactPath,
			behavior,
		)
		if err != nil {
			return err
		}
		if err = os.MkdirAll(destination, 0o700); err != nil {
			return planningError(
				ErrorSideEffect,
				fieldPreparationDestination,
				"cannot create artifact directory",
				err,
			)
		}
	}
	info, err := os.Lstat(destination)
	if err != nil {
		return planningError(
			ErrorSideEffect,
			fieldPreparationDestination,
			"cannot inspect artifact directory",
			err,
		)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
		return &Error{
			Code: ErrorUnsupported, Field: fieldPreparationDestination,
			Behavior: behavior, Message: "artifact directory destination has another file type",
		}
	}
	if err = applyGeneratedArtifactMetadata(
		destination,
		false,
		uid,
		gid,
		nil,
	); err == nil {
		err = os.Chmod(destination, os.FileMode(mode))
	}
	if err == nil {
		err = applyGeneratedArtifactMetadata(
			destination,
			false,
			nil,
			nil,
			extendedAttributes,
		)
	}
	if err != nil {
		return planningError(
			ErrorSideEffect,
			fieldPreparationDestination,
			"cannot apply artifact directory metadata",
			err,
		)
	}

	return nil
}

func prepareArtifactDestination(
	artifactRoot,
	nodeID,
	artifactPath,
	behavior string,
) (string, error) {
	nodeRoot := filepath.Join(artifactRoot, ArtifactNodeDirectory(nodeID))
	destination := filepath.Join(nodeRoot, filepath.FromSlash(artifactPath))
	relative, err := filepath.Rel(nodeRoot, destination)
	if err != nil || relative == "." || relative == ".." || filepath.IsAbs(relative) ||
		strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		return "", &Error{
			Code: ErrorInvalidInput, Field: fieldPreparationDestination,
			Behavior: behavior, Message: "artifact path escapes its Node root",
		}
	}
	if err = ensureNoSymlinkParents(nodeRoot, filepath.Dir(destination)); err != nil {
		return "", err
	}
	if err = os.MkdirAll(filepath.Dir(destination), 0o700); err != nil {
		return "", planningError(
			ErrorSideEffect,
			fieldPreparationDestination,
			"cannot create artifact directory",
			err,
		)
	}

	return destination, nil
}

func ensureNoSymlinkParents(root, directory string) error {
	if err := os.MkdirAll(root, 0o700); err != nil {
		return planningError(
			ErrorSideEffect,
			fieldPreparationDestination,
			"cannot create Node root",
			err,
		)
	}
	rootInfo, err := os.Lstat(root)
	if err != nil {
		return planningError(
			ErrorSideEffect,
			fieldPreparationDestination,
			"cannot inspect Node root",
			err,
		)
	}
	if rootInfo.Mode()&os.ModeSymlink != 0 || !rootInfo.IsDir() {
		return &Error{
			Code: ErrorUnsupported, Field: fieldPreparationDestination,
			Behavior: behaviorArtifactGeneration,
			Message:  "artifact Node root is not a real directory",
		}
	}
	relative, err := filepath.Rel(root, directory)
	if err != nil {
		return planningError(
			ErrorInvalidInput,
			fieldPreparationDestination,
			"cannot resolve path",
			err,
		)
	}
	current := root
	for part := range strings.SplitSeq(relative, string(filepath.Separator)) {
		if part == "" || part == "." {
			continue
		}
		current = filepath.Join(current, part)
		info, statErr := os.Lstat(current)
		if os.IsNotExist(statErr) {
			continue
		}
		if statErr != nil {
			return planningError(
				ErrorSideEffect,
				fieldPreparationDestination,
				"cannot inspect artifact path",
				statErr,
			)
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return &Error{
				Code: ErrorUnsupported, Field: fieldPreparationDestination,
				Behavior: behaviorArtifactGeneration,
				Message:  "artifact path contains a symbolic link",
			}
		}
	}

	return nil
}
