//nolint:nlreturn,wsl_v5 // Ordered document rendering is clearer without whitespace-only expansion.
package compatibility

import (
	"bytes"
	"fmt"
	"slices"
	"strings"
)

// DefaultDocumentationPath is the generated user-facing compatibility inventory.
const DefaultDocumentationPath = "docs/compatibility.mdx"

// RenderDocumentation produces the user-facing compatibility inventory from the
// same manifest used by the source and version gates. Keep this renderer free of
// repository I/O so tests can compare its output byte-for-byte.
//
//nolint:lll // Long raw-string lines are intentional generated Markdown content.
func RenderDocumentation(baseline *Baseline) []byte {
	var output bytes.Buffer

	fmt.Fprintf(&output, `---
title: Containerlab compatibility
description: Pinned containerlab module identity and direct-runtime capability inventory.
icon: ListChecks
---

{/* Code generated by cmd/compatibility. DO NOT EDIT. */}

Clabernetes consumes containerlab **%s** (`+"`%s`"+`) as an unmodified Go module.
The machine-readable source is `+"`%s`"+`. The imported live registry is the only
kind and alias inventory: c9s does not commit or maintain a second kind catalog.

Updating the pinned module automatically exposes every newly registered kind to the
same generic planner and conformance flow. Compatibility verification rejects module
identity drift or a generic operation that Kubernetes cannot represent; it does not
require a c9s row, switch, fixture, or adapter for a new kind name.

| Baseline property | Value |
| --- | --- |
| Containerlab version | `+"`%s`"+` |
| Upstream commit | `+"`%s`"+` |
| Kind inventory | live imported registry |
| Plan schema | `+"`%s`"+` |
`, baseline.Containerlab.Version, baseline.Containerlab.Commit, DefaultBaselinePath,
		baseline.Containerlab.Version, baseline.Containerlab.Commit, baseline.PlanSchemaVersion)

	output.WriteString(`
## Behavior inventory

The current-realization column describes the implementation available during migration:

- ` + "`controller-native`" + `: already owned by a Kubernetes controller or compiler.
- ` + "`nested-only`" + `: implemented only through the nested containerlab/Docker launcher.
- ` + "`partial`" + `: some paths exist, but required behavior is incomplete.
- ` + "`missing`" + `: no current implementation exists.

| Category | Behavior | Inputs | Required capabilities | Required scenarios | Current realization |
| --- | --- | --- | --- | --- | --- |
`)

	behaviors := slices.Clone(baseline.Behaviors)
	slices.SortFunc(behaviors, func(left, right Behavior) int {
		if comparison := strings.Compare(left.Category, right.Category); comparison != 0 {
			return comparison
		}
		return strings.Compare(left.ID, right.ID)
	})
	for index := range behaviors {
		behavior := &behaviors[index]
		fmt.Fprintf(
			&output,
			"| %s | %s | %s | %s | %s | %s |\n",
			code(behavior.Category),
			code(behavior.ID),
			codeList(behavior.Inputs),
			codeList(
				behavior.RequiredCapabilities,
			),
			codeList(behavior.Scenarios),
			code(behavior.State),
		)
	}

	output.WriteString(`
## Capability contract

Every compatible kind discovered from the live registry must satisfy every applicable
generic capability and scenario. Behavior rows define the API and operational
requirements used to generate those conformance runs.

| Capability | Requirement |
| --- | --- |
`)

	capabilities := slices.Clone(baseline.Capabilities)
	slices.SortFunc(capabilities, func(left, right Capability) int {
		return strings.Compare(left.ID, right.ID)
	})
	for _, capability := range capabilities {
		fmt.Fprintf(
			&output,
			"| %s | %s |\n",
			code(capability.ID),
			markdownCell(capability.Description),
		)
	}

	output.WriteString(`
## Baseline updates

A containerlab version change is an explicit compatibility event. Update the pinned
module identity and dependency lock data together. ` + "`make verify-containerlab-compatibility`" + `
validates that identity and discovers the registry live; additions and aliases do not
require c9s catalog edits. Generic behavior gaps still fail conformance.
`)

	return output.Bytes()
}

func code(value string) string {
	return "`" + strings.ReplaceAll(markdownCell(value), "`", "\\`") + "`"
}

func codeList(values []string) string {
	if len(values) == 0 {
		return "—"
	}

	items := make([]string, 0, len(values))
	for _, value := range values {
		items = append(items, code(value))
	}
	return strings.Join(items, ", ")
}

func markdownCell(value string) string {
	value = strings.ReplaceAll(value, "|", "\\|")
	value = strings.ReplaceAll(value, "\n", " ")
	return value
}
