import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderCrdViewer } from '../app/lib/crd-viewer/core';
import { getRepoRoot } from '../app/lib/crd-viewer/paths';

const repoRoot = getRepoRoot();
const outFile = path.resolve(
  fileURLToPath(new URL('../app/generated/crd-views.ts', import.meta.url)),
);

const entries: Array<{
  key: string;
  src: string;
  showStatus: boolean;
}> = [
    { key: 'topology', src: 'assets/crd/c9s.run_topologies.yaml', showStatus: false },
    { key: 'node', src: 'assets/crd/c9s.run_nodes.yaml', showStatus: true },
    { key: 'link', src: 'assets/crd/c9s.run_links.yaml', showStatus: true },
    { key: 'launcher-profile', src: 'assets/crd/c9s.run_launcherprofiles.yaml', showStatus: true },
    { key: 'config', src: 'assets/crd/c9s.run_configs.yaml', showStatus: true },
  ];

const views: Record<string, string> = {};

for (const entry of entries) {
  views[entry.key] = renderCrdViewer(repoRoot, entry.src, {
    showStatus: entry.showStatus,
  });
}

const body = `/** Generated by scripts/generate-crd-views.ts — do not edit. */\n\nexport const crdViews: Record<string, string> = ${JSON.stringify(views)};\n`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, body, 'utf-8');

console.log(`Generated ${Object.keys(views).length} CRD views → ${outFile}`);
