---
apiVersion: c9s.run/v1alpha1
kind: LauncherProfile
metadata:
  name: direct
spec:
  expose:
    disableAutoExpose: true
---
apiVersion: c9s.run/v1alpha1
kind: Link
metadata:
  name: srl1-e1-1-srl2-e1-1
spec:
  endpointA:
    nodeName: srl1
    interfaceName: e1-1
  endpointB:
    nodeName: srl2
    interfaceName: e1-1
  connectivity: vxlan
---
apiVersion: c9s.run/v1alpha1
kind: Node
metadata:
  name: srl1
  labels:
    c9s.run/mode: direct
spec:
  kind: nokia_srlinux
  image: ghcr.io/nokia/srlinux
  launcherProfileRef:
    name: direct
  startup-config: |
    set / interface ethernet-1/1 admin-state enable
    set / interface ethernet-1/1 subinterface 0
    set / interface ethernet-1/1 subinterface 0 ipv4
    set / interface ethernet-1/1 subinterface 0 ipv4 admin-state enable
    set / interface ethernet-1/1 subinterface 0 ipv4 address 192.168.0.0/31
    set / network-instance default
    set / network-instance default interface ethernet-1/1.0
---
apiVersion: c9s.run/v1alpha1
kind: Node
metadata:
  name: srl2
  labels:
    c9s.run/mode: direct
spec:
  kind: nokia_srlinux
  image: ghcr.io/nokia/srlinux
  launcherProfileRef:
    name: direct
  startup-config: |
    set / interface ethernet-1/1 admin-state enable
    set / interface ethernet-1/1 subinterface 0
    set / interface ethernet-1/1 subinterface 0 ipv4
    set / interface ethernet-1/1 subinterface 0 ipv4 admin-state enable
    set / interface ethernet-1/1 subinterface 0 ipv4 address 192.168.0.1/31
    set / network-instance default
    set / network-instance default interface ethernet-1/1.0
