package conformance_test

import (
	"context"
	"os"
	"os/exec"
	"strings"
	"testing"
	"time"

	clabernetesinternalconformance "github.com/clabernetes/clabernetes/internal/conformance"
	clabernetesinternaldeviceplan "github.com/clabernetes/clabernetes/internal/deviceplan"
	clabernetestesthelper "github.com/clabernetes/clabernetes/testhelper"
)

const suiteEnvironment = "C9S_DIRECT_CONFORMANCE_SUITE"

const cleanupTimeout = 2 * time.Minute

func TestMain(m *testing.M) {
	clabernetestesthelper.Flags()

	os.Exit(m.Run())
}

func TestEveryEnvironmentAvailableImageRunsDirectly(t *testing.T) {
	suitePath := strings.TrimSpace(os.Getenv(suiteEnvironment))
	if suitePath == "" {
		t.Skip(suiteEnvironment + " is not set")
	}

	suite, inventories, err := clabernetesinternalconformance.LoadSuite(
		suitePath,
		clabernetesinternaldeviceplan.NewContainerlabRegistry(),
	)
	if err != nil {
		t.Fatal(err)
	}

	for index := range suite.Scenarios {
		scenario := &suite.Scenarios[index]
		inventory := &inventories[index]

		t.Run(scenario.ID, func(t *testing.T) {
			runScenario(t, scenario, inventory)
		})
	}
}

func runScenario(
	t *testing.T,
	scenario *clabernetesinternalconformance.Scenario,
	inventory *clabernetesinternalconformance.ScenarioInventory,
) {
	t.Helper()

	namespace := clabernetestesthelper.NewTestNamespace("direct-conformance-" + scenario.ID)
	clabernetestesthelper.KubectlCreateNamespace(t, namespace)

	defer cleanupScenario(t, namespace, scenario.ID)

	t.Logf(
		"running %s image observations from the live registry: %+v",
		inventory.Availability,
		inventory.Images,
	)
	applyManifest(t, namespace, scenario.Manifest)

	for _, image := range inventory.Images {
		waitForNodeReady(t, namespace, image.Node, scenario.ResolvedTimeout)
	}

	for index := range scenario.Management {
		waitForObservation(t, namespace, "management", &scenario.Management[index], scenario)
	}

	for index := range scenario.Dataplane {
		waitForObservation(t, namespace, "dataplane", &scenario.Dataplane[index], scenario)
	}
}

func applyManifest(t *testing.T, namespace, manifest string) {
	t.Helper()

	cmd := exec.CommandContext( //nolint:gosec // Arguments and manifest come from the selected suite.
		t.Context(),
		"kubectl",
		"apply",
		"--namespace",
		namespace,
		"-f",
		"-",
	)
	cmd.Stdin = strings.NewReader(manifest)

	clabernetestesthelper.Execute(t, cmd)
}

func waitForNodeReady(t *testing.T, namespace, node string, timeout time.Duration) {
	t.Helper()

	cmd := exec.CommandContext( //nolint:gosec // Identities are validated suite data.
		t.Context(),
		"kubectl",
		"wait",
		"--namespace",
		namespace,
		"--for=jsonpath={.status.readiness}=ready",
		"--timeout="+timeout.String(),
		"node.c9s.run/"+node,
	)

	clabernetestesthelper.Execute(t, cmd)
}

func waitForObservation(
	t *testing.T,
	namespace,
	category string,
	observation *clabernetesinternalconformance.ExecObservation,
	scenario *clabernetesinternalconformance.Scenario,
) {
	t.Helper()

	deadline := time.NewTimer(scenario.ResolvedTimeout)
	defer deadline.Stop()

	ticker := time.NewTicker(scenario.ResolvedPollInterval)
	defer ticker.Stop()

	var lastOutput []byte

	var lastErr error

	for {
		args := []string{"exec", "--namespace", namespace, observation.Target}
		if observation.Container != "" {
			args = append(args, "--container", observation.Container)
		}

		args = append(args, "--")
		args = append(args, observation.Command...)

		cmd := exec.CommandContext( //nolint:gosec // The external suite owns executable observations.
			t.Context(),
			"kubectl",
			args...,
		)

		lastOutput, lastErr = cmd.CombinedOutput()
		if lastErr == nil {
			return
		}

		select {
		case <-t.Context().Done():
			t.Fatalf(
				"%s observation %q canceled: %v: %s",
				category,
				observation.Name,
				lastErr,
				strings.TrimSpace(string(lastOutput)),
			)
		case <-deadline.C:
			t.Fatalf(
				"%s observation %q did not pass: %v: %s",
				category,
				observation.Name,
				lastErr,
				strings.TrimSpace(string(lastOutput)),
			)
		case <-ticker.C:
		}
	}
}

func cleanupScenario(t *testing.T, namespace, scenarioID string) {
	t.Helper()

	if *clabernetestesthelper.SkipCleanup {
		t.Logf("retaining conformance namespace %q for scenario %q", namespace, scenarioID)

		return
	}

	cleanupContext, cancel := context.WithTimeout(context.Background(), cleanupTimeout)
	defer cancel()

	cmd := exec.CommandContext( //nolint:gosec // Namespace is generated by this test.
		cleanupContext,
		"kubectl",
		"delete",
		"namespace",
		namespace,
		"--wait=true",
	)

	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Errorf("delete conformance namespace %q: %v: %s", namespace, err, output)

		return
	}

	cmd = exec.CommandContext( //nolint:gosec // Namespace is generated by this test.
		cleanupContext,
		"kubectl",
		"get",
		"namespace",
		namespace,
		"--ignore-not-found=true",
		"--output=name",
	)

	output, err = cmd.CombinedOutput()
	if err != nil {
		t.Errorf("verify conformance namespace cleanup %q: %v: %s", namespace, err, output)

		return
	}

	if strings.TrimSpace(string(output)) != "" {
		t.Errorf(
			"conformance namespace %q remains after scenario %q: %s",
			namespace,
			scenarioID,
			output,
		)
	}
}
