---
apiVersion: v1
kind: Secret
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    revision: "{{ .Release.Revision }}"
    c9s.run/app: {{ .Values.appName }}
    c9s.run/name: "{{ .Values.appName }}-certificate"
    c9s.run/component: certificate
    c9s.run/part-of: manager
    {{- if .Values.globalLabels }}
{{ .Values.globalLabels | toYaml | indent 4 }}
    {{- end }}
  {{- if .Values.globalAnnotations }}
  annotations:
{{ .Values.globalAnnotations | toYaml | indent 4 }}
  {{- end }}
  name: "{{ .Values.appName }}-certificate"
data: {}