apiVersion: c9s.run/v1alpha1
kind: Node
metadata:
  annotations: {}
  labels:
    c9s.run/mode: direct
  name: srl1
  namespace: NAMESPACE
spec:
  image: ghcr.io/nokia/srlinux
  kind: nokia_srlinux
  launcherProfileRef:
    name: direct
status:
  appliedLauncherProfile:
    name: direct
