apiVersion: v1
kind: Service
metadata:
  labels:
    clabernetes/app: clabernetes
    clabernetes/name: srl2-vx
    clabernetes/topologyNode: srl2
    clabernetes/topologyServiceType: fabric
  name: srl2-vx
  namespace: NAMESPACE
  ownerReferences:
    - apiVersion: c9s.run/v1alpha1
      kind: Node
      name: srl2
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: vxlan
      port: 14789
      protocol: UDP
      targetPort: 14789
    - name: slurpeeth
      port: 4799
      protocol: TCP
      targetPort: 4799
  selector:
    clabernetes/app: clabernetes
    clabernetes/name: srl2
    clabernetes/topologyNode: srl2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
