---
name: Deploy docs (main)

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: docs-production-deploy
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/docs-deploy.yaml
    with:
      ref: main
      deploy-message: "docs production for main (${{ github.sha }})"
    secrets: inherit
